### PR TITLE
link with libXrdPfc instead of libXrdFileCache for Xrootd-5

### PR DESCRIPTION
**Pull request by ddavila0**

### CODE REVIEW

**Comment by brianhlin** [comment]
Can we ifdef this somehow so that we can build for both XRootD 4 and XRootD 5 (in case of say another XRootD 4 release)?

**Comment by wyang007** [comment]
the .so will have a dependency on libXrdPfc so I guess OSG will need to build a rpm for xrootd 4.x and another rpm for xrootd 5.x.

**Comment by brianhlin** [comment]
Yeah, it would be nice to be able to use the same version of the plugin across the two. Can't we throw some logic into the Makefile so that it picks the appropriate library to link depending on the XRootD version?

**Comment by wyang007** [comment]
I am not sure putting logic in the Makefile will help. "ldd XrdName2NameDCP4RUCIO.so" will show that this plugin has a dependency on libXrdFileCache.so. I wish the Xrootd RPMs have a link from libXrdPfs.so -> libXrdFileCache.so

**Comment by brianhlin** [comment]
Can we ask them to do that instead of making this change?

**Pull request merged**
